# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # Link to your container registry. You will launch it in Yandex Cloud.
  repository: Скрыл по просьбе Яндекс Практикума
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 'v2024-12-17-r1'

containerPort: Скрыл по просьбе Яндекс Практикума

config:
  KAFKA_HOST: Скрыл по просьбе Яндекс Практикума
  KAFKA_PORT: "Скрыл по просьбе Яндекс Практикума"
  KAFKA_CONSUMER_USERNAME: Скрыл по просьбе Яндекс Практикума
  KAFKA_CONSUMER_PASSWORD: Скрыл по просьбе Яндекс Практикума
  KAFKA_CONSUMER_GROUP: Скрыл по просьбе Яндекс Практикума
  KAFKA_SOURCE_TOPIC: dds-service-orders
  KAFKA_DESTINATION_TOPIC: dds-service-orders

  PG_WAREHOUSE_HOST: Скрыл по просьбе Яндекс Практикума
  PG_WAREHOUSE_PORT: 'Скрыл по просьбе Яндекс Практикума'
  PG_WAREHOUSE_DBNAME: Скрыл по просьбе Яндекс Практикума
  PG_WAREHOUSE_USER: Скрыл по просьбе Яндекс Практикума
  PG_WAREHOUSE_PASSWORD: Скрыл по просьбе Яндекс Практикума


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
